-- Demo-Daten für die Offline-Erfassung (als Parsing Schema der App ausführen, z. B. HR)
-- Die Offline-Schicht selbst braucht KEINE Datenbankobjekte. Diese Tabelle ist nur das Beispiel,
-- auf dem die native Formularseite arbeitet.
set define off

create table oe_auftrag (
    id             number generated by default on null as identity primary key,
    nr             varchar2(20)   not null,
    titel          varchar2(200)  not null,
    kunde          varchar2(200),
    ort            varchar2(200),
    status         varchar2(20)   default 'OFFEN' not null
                   constraint oe_auftrag_status_ck check (status in ('OFFEN', 'IN_ARBEIT', 'ERLEDIGT')),
    erledigt_am    date,
    messwert       number,
    asset_code     varchar2(200),
    befund         varchar2(4000),
    unterschrift   clob,
    unterzeichner  varchar2(200),
    created_at     date           default sysdate not null,
    created_by     varchar2(255)  not null,
    updated_at     date           default sysdate not null,
    updated_by     varchar2(255)  not null
);

comment on table oe_auftrag is 'Beispiel für die Offline-Erfassung: Aufträge, die offline bearbeitet und protokolliert werden';
comment on column oe_auftrag.unterschrift is 'Unterschrift als Bild (Data-URL), erfasst mit der CSS-Klasse offline-signature';

create or replace trigger oe_auftrag_biu
    before insert or update on oe_auftrag
    for each row
declare
    l_user varchar2(255) := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
begin
    if inserting then
        :new.created_at := sysdate;
        :new.created_by := l_user;
    end if;
    :new.updated_at := sysdate;
    :new.updated_by := l_user;
end;
/

insert into oe_auftrag (nr, titel, kunde, ort) values ('A-1001', 'Wartung Heizungsanlage', 'Stadtwerke Nord', 'Hauptstraße 12, Kiel');
insert into oe_auftrag (nr, titel, kunde, ort) values ('A-1002', 'Zählerwechsel', 'Wohnbau Süd', 'Am Markt 3, Ulm');
insert into oe_auftrag (nr, titel, kunde, ort) values ('A-1003', 'Störung Lüftung', 'Klinikum West', 'Parkweg 7, Aachen');
insert into oe_auftrag (nr, titel, kunde, ort) values ('A-1004', 'Prüfung Brandschutzklappen', 'Schule am See', 'Seestraße 1, Plön');
insert into oe_auftrag (nr, titel, kunde, ort) values ('A-1005', 'Inbetriebnahme Wärmepumpe', 'Familie Berger', 'Lindenweg 22, Celle');
commit;
