-- Fotos zu Aufträgen (Beispiel für die CSS-Klasse offline-photo): beliebig viele je Auftrag
create table oe_auftrag_foto (
    id          number generated by default on null as identity primary key,
    auftrag_id  number         not null
                constraint oe_auftrag_foto_auftrag_fk references oe_auftrag (id) on delete cascade,
    foto        clob           not null,
    bemerkung   varchar2(400),
    created_at  date           default sysdate not null,
    created_by  varchar2(255)  not null,
    updated_at  date           default sysdate not null,
    updated_by  varchar2(255)  not null
);

create index oe_auftrag_foto_auftrag_ix on oe_auftrag_foto (auftrag_id);

comment on table oe_auftrag_foto is 'Fotos zu Aufträgen, offline aufgenommen und über die native Formularseite 4 gespeichert';
comment on column oe_auftrag_foto.foto is 'Bild als Data-URL (JPEG, im Browser auf höchstens 1600 Pixel verkleinert)';

create or replace trigger oe_auftrag_foto_biu
    before insert or update on oe_auftrag_foto
    for each row
declare
    l_user varchar2(255) := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
begin
    if inserting then
        :new.created_at := sysdate;
        :new.created_by := l_user;
    end if;
    :new.updated_at := sysdate;
    :new.updated_by := l_user;
end;
/
